### ISSUE TITLE
Website - Store info

### ISSUE THREAD

**Issue by andy-dandy** [pramslam/IndieGameCon#21]
# 2017 Items

1. Poster
    * Price: $5
    * Description: Made by a local artist in Eugene (need name). This features game art from all of the developer games featured in 2017.
    * Dimensions: 
    * Image 1 = computer design
    * Image 2 = pic of it IRL

2. T-shirt
    * Price: $15
    * Description: References Bitforest and ties in the videogame theme with a game gem
    * Sizes: S - 3XL
    * Color: Blue with white lines
    * Image 1 =  
![2018 t-shirt proof design focus](https://user-images.githubusercontent.com/46360897/50675638-3208c700-0fa4-11e9-81d9-aba6cc4ec4ab.png)

    * Image 2 = 
![2018 t-shirt proof human focus](https://user-images.githubusercontent.com/46360897/50675662-4cdb3b80-0fa4-11e9-8f11-3440179a2453.png)

# 2018 Items
1. Poster
    * Price: $5
    * Description: Features the updated Indie Game Con logo for 2018, created by Ashley Levy and edited by Andy Darnall.
    * Dimensions: 11 in x 17 in / ~30 cm x 40 cm
    * Image 1 = 
[IndieGameCon_Poster_2018.pdf](https://github.com/pramslam/IndieGameCon/files/2731149/IndieGameCon_Poster_2018.pdf)

    * Image 2 = pic of it IRL

2. IGC 2018 T-shirt
    * Price: $15
    * Description: Made by Andy Darnall with edited public domain vectors. Inspired by the emerging virtual reality field, with a Bitforest touch.
    * Sizes: S - XL
    * Color: Black background with white lines
    * Image 1 = 
![2018 t-shirt proof frontside](https://user-images.githubusercontent.com/46360897/50675845-79438780-0fa5-11e9-812f-cf498337621e.jpg)

    * Image 2 = 
![2018 t-shirt proof backside](https://user-images.githubusercontent.com/46360897/50675847-7d6fa500-0fa5-11e9-9662-305242f0d0a9.jpg)

    * Image 3 = 
![2018 t-shirt proof - both sides zoomed in](https://user-images.githubusercontent.com/46360897/50675851-89f3fd80-0fa5-11e9-901b-122d858e5dfd.jpg)

**Comment by pramslam** [comment]
We are not doing an online store.
