### ISSUE TITLE
Website - Home

### ISSUE THREAD

**Issue by pramslam** [pramslam/IndieGameCon#22]
- [ ] Explainer Video
- [x] Who, What, Where, When?
- [x] Buy tickets here, eventbrite
- [x] Code of Conduct

**Comment by andy-dandy** [comment]
Take the exactl rectangle with text on igc's current home page and paste it where the open eugene explainer video on the homepage is

**Comment by andy-dandy** [comment]
Code of conduct: don't link to github, make an actual page

**Comment by andy-dandy** [comment]
[IGC Logo_Black_White Background.pdf](https://github.com/pramslam/IndieGameCon/files/2731110/IGC.Logo_Black_White.Background.pdf)


This is the new logo to replace the old logo

**Comment by andy-dandy** [comment]
mailchimp account for newsletter

user: indiegamecon@gmail.com
password: ILoveIGC!1

**Comment by andy-dandy** [comment]
For mailchimp newsletter signup box, have them only give their first name and email, and a generic "we hate spam and won't share your information with anyone" note. Then a "Thank you! We'll stay in touch" after they click sign-up.

**Comment by pramslam** [comment]
Content Post!!!

Indie Game Con
Presented By...
TITLE SPONSOR

Site Navigation: Home, Games, Panels, Schedule, Sponsors, Media, About, Store

What is Indie Game Con?

It’s tricky to market a game with no budget, and it’s difficult to labor in solitude on a passion project. But when strangers pick up the controller and start to laugh and smile, it all seems worth it. And when you meet fellow creators who understand the highs and lows of indie game development, you feel like you’ve found your tribe.

That’s why Indie Game Con exists: to put creator-owned games in front of mainstream audiences, and build a space where game developers can hang out with their own.

IGC has been an annual event in Eugene, Oregon since 2013, and is run by Bitforest, a non-profit organization sponsored by Innovate Oregon. Directed by Ted Brown and run by volunteer tech and game dev professionals, it’s an expression of the inclusive game community in Eugene and beyond.

Signup as a Contributor, Volunteer, or Buy a Ticket on Eventbrite or Facebook
- https://www.eventbrite.com/e/indie-game-con-2019-tickets-54520160267

/* Might need to rework this section a bit
What kind of things will be at Indie Game Con?
- Playable Indie video games!
- Developer Panels
- Programming Demos
- Art Demos

What does "indie" mean?
- Not belonging to or affiliated with a major game company.

Who should come to indie game con?
- Game Developers indie or not!
- Interested in Tech
- Kids!
*/

Join the conversation on the #indiegamecon2019 channel of the EugeneTech Slack http://eugslack.com
- Link to our slack

When and Where
- Saturday & Sunday, November 9 & 10
- Venue TBD, Map

Want to submit a game or check out submitted games?
- Link to game submission page

View Code of Conduct
- Link to Code of Conduct, make into page not a link to a github page

**Comment by pramslam** [comment]
This is done, we need a better explainer video but that can wait. I made a new issue
