### ISSUE TITLE
Website - Games

### ISSUE THREAD

**Issue by pramslam** [pramslam/IndieGameCon#23]
- [x] Submit Game (form)
- [x] List of submitted games
- [x] List of submitted developers
- [ ] Game Submission FAQ

**Comment by mckelveygreg** [comment]
I can make forms that baked in to the website now, so users don't have to leave our site to sign up for things. I'll pretty much do what you have in your google form, and then it will just need to be checked for content.

**Comment by mckelveygreg** [comment]
Do we have a list of FAQs for devs? Like what they need to know?

**Comment by pramslam** [comment]
Working on it!
https://docs.google.com/document/d/1XB46AbpkpbtuKXr6NERzKYRou4L4t7GPjLYa2hxW9dk/edit?usp=sharing

**Comment by pramslam** [comment]
I removed an issue and moved it here

Game submitter thank you letter
- After a game is submitted, they are taken to a thank you page, that directs them to purchase a tickets through eventbrite

**Comment by pramslam** [comment]
Rudimentary Game submission faq. Still needs an update, made a new issue
