### ISSUE TITLE
Website - Sponsors

### ISSUE THREAD

**Issue by pramslam** [pramslam/IndieGameCon#26]
- [x] Title Sponsor
- [x] Presenting Sponsors
- [x] Supporting Sponsors
- [x] Community Sponsors

**Comment by andy-dandy** [comment]
This obviously can't be done until we've reached out to sponsors, so for now we will just have past sponsors on this page

**Comment by mckelveygreg** [comment]
Do we need a list of FAQs or something that sponsors would need to know?

**Comment by pramslam** [comment]
# Sponsorship FAQ

## Why should I sponsor Indie Game Con?
An Indie Game Con sponsorship puts you in front of hundreds of passionate game developers and consumers. In previous years, we have had 400 individuals attend our event. Not only can your sponsorship promote a service, a brand, or a product, it will boost our spending on advertising, and help continue Indie Game Con as an Oregon tradition.

## What do you get?
### Community Partner Sponsorship
Partner logo cloud on t-shirt
Contact us for how you can help!  // Make Contact Us a link to indiegamecon@gmail.com

### Supporting Level Sponsorship
Medium logo placement on t-shirts
Listing on all PR media, social media, etc.
5 minute ad between panel setup

### Presenting Sponsorship
Large logo placement on t-shirts
Exhibit space
Listing on all PR media, social media, etc.
20 minute presentation (optional)

### Title Sponsorship
Listing on all PR media, Social media, etc.
“Presented by [your name]” title sponsorship
Prominent logo placement on t-shirts
Exhibit space
Listing on all PR media, social media, etc.
Opening comments

## When is Indie Game Con?
Indie Game Con will be happening Saturday & Sunday, November 9 & 10, 2019.

## Who do I contact?
David Lo, Mike Jones, Greg McKelvey, Andy Darnall

## How do you sponsor?
Indie Game Con is a Bitforest project. Bitforest is a fiscally-sponsored 501(c)3 nonprofit organization that instills an innovation culture in Oregon communities. If you would like to donate to Bitforest, make your check Payable to “Bitforest ℅ TAO Foundation” and note “Indie Game Con” in the memo. 

If you do not need a 501(c)3 paper receipt, you can donate through our Eventbrite link: *insert link*

**Comment by pramslam** [comment]
Sponsor FAQ up, we will add sponsor icons as they are onboarded.
