### ISSUE TITLE
Website - Sponsorship Donation

### ISSUE THREAD

**Issue by andy-dandy** [pramslam/IndieGameCon#40]
Should be hosted on bitforest.co

Should be a secret link that only sponsors have

**Comment by pramslam** [comment]
INDIE GAME CON DONATION
$1.00

Bitforest is the fiscal sponsor of the Indie Game Con – December 9-10. Donations using this link will go to directly to Indie Game Con helping make the event awesome.  Find out more at http://www.indiegamecon.com

**Comment by pramslam** [comment]
I need the bit.ly for IndieGameCon donation link from eventbrite. The eventbrite is still hosted under my account. I will remake one tonight under IndieGameCon's gmail account? Or should that be made by bitforest?

**Comment by pramslam** [comment]
This has been figured out. If a charity receipt is needed, they must write a check. If a receipt is not needed, donate through eventbrite.
