### ISSUE TITLE
Eventbrite Ticket

### ISSUE THREAD

**Issue by pramslam** [pramslam/IndieGameCon#43]
I made an eventbrite event to see how it all works. But with no art and stuff, it looks sad

https://www.eventbrite.com/e/indie-game-con-2019-tickets-54520160267

**Comment by andy-dandy** [comment]
Art competition for banner - winner gets t-shirt and their art on website

Connect any forms necessary to any selection, i.e. volunteer order needs to connect to volunteer form

**Comment by pramslam** [comment]
So bitforest already has a eventbrite that was used for 2014 and 2015. It is not tied to the indiegamecon@gmail.com. I'm going to contact mike for access.

**Comment by pramslam** [comment]
Emily is working on this.

**Comment by pramslam** [comment]
Senior, student, tribal and military discount tickets

**Comment by pramslam** [comment]
Transfered Eventbrite over to IndieGameCon account. Mike jones is adding indiegamecon@gmail.com as a bitforest event organizer.
