### ISSUE TITLE
Marketing Art

### ISSUE THREAD

**Issue by mckelveygreg** [pramslam/IndieGameCon#45]
Let's make a folder here or in drive that has all of our Logos, pictures, banners, art, fodder, etc

**Comment by andy-dandy** [comment]
Andy is doing color stuff

**Comment by andy-dandy** [comment]
Decide what will be a contest for local artists to contribute to for the website or posters/t-shirts

**Comment by pramslam** [comment]
closing because this was already done.

Moving to separate issue
> Andy is doing color stuff
> Decide what will be a contest for local artists to contribute to for the website or posters/t-shirts
