### ISSUE TITLE
Website philosophy

### ISSUE THREAD

**Issue by mckelveygreg** [pramslam/IndieGameCon#46]
Let's answer these questions: 
- [x] Who is our audience?
- [x] How does our audience change over time?
- [x] Page audience
  - [x] Homepage - 
  - [x] Games - 
  - [x] Panels - 
  - [x] About page - 
  - [x] Ticketing Page -

**Comment by pramslam** [comment]
Who is our audience?
General Audience (GA), Developers (Devs), Sponsors ($$$)

How does our audience change over time?
* Sponsors will be most important initially, to get them onboarded and ensure we secure the funds to do indie game con
* Devs are next, to get them onboarded and submitting game content
* GA is last, to give them information about the convention, schedule, and purchase tickets

Page audience
* Homepage - All Audiences, single place where all information/links are displayed
* Games - Devs who want to submit games
* Panels - Devs, GA who want to see the content at indie game con
* About page - Sponsors, Devs, who want to see who was involved
* Ticketing Page - All Audiences will use this page to buy tickets or send donations

Hope this answered all your questions, let me know if I missed anything or if you have anything to add!

**Comment by pramslam** [comment]
@mckelveygreg Closing this issue, reopen it if you still need it on the issues list
